### ISSUE TITLE
By Folder zeigt mir nichts an

### ISSUE THREAD

**Issue by sergem1** [DonDavici/DreamPlex#146]
Wenn ich andere Versionen von dreamplex installiere,zum Beispiel 1.09 oder die aktuelle 1.09.7 und unter ‘ByFolder‘ gehe sehe ich zwar meinen Kategorien die ich erstellt habe ( Disney, Dokumentation, Thriller ,usw.) aber keinen Filmen unter diesen Kategorien.
Wenn ich bei ´All Videos´ gehe da sind alle Filmen da. Finde das komisch weil mit der Version 1.08.3 da klappt alles,und die versionen die danach rausgekommen sind immer der selbe problem.
Fehlt mir vielleicht irgendwelche datei oder etwas falsch konfiguriert? Zur info habe eine Vusolo 2 mit Vti 6.0.5 ( habe auch schon anderen image draufgespielt und da habe ich auch das gleiche problem)
Kanns du mir bitte weiterhelfen
Vielen Dank

**Comment by paraxenos** [comment]
Servus und ein gutes neues Jahr!

Habe meine Vu+ Duo2 auf das neuste VTi Image (8.0.0) geflasht und wollte
eben die aktuellste Dreamplex Version wieder installieren ( 2.0.3 Irrtum
Vorbehalt).

Irgendwie habe ich ein Problemchen. Ich gehe auf manuelle Installation von
ipk Paketen und die Installation startet und endet auch  (mit der Meldung
"have Fun"), dann kann ich aber die Dreamplex Anwendung nirgenswo finden :-(

Habe auch gesehen dass meine letzte 1.09.8 über 2Mb gross war, die aktuelle
bloss noch etwas über 700kB.

Was mache ich falsch? Danke für ein kurzes Feedback....

Gruss
Paraxenos



Am 18. August 2014 um 19:26 schrieb Bender <notifications@github.com>:

> Nein, die fertige 2.0 ist noch nicht da, jedoch die öffentlich zugängliche
> RC8, die halt ggf. noch ein paar Bugs haben kann. Zu finden auf
> bintray.com suche Dreamplex
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DonDavici/DreamPlex/issues/146#issuecomment-52525327>.
>



-- 
____________________________________________________________________
Andreas Karoussatos, Einfangstrasse 5, CH-8304 Wallisellen, Switzerland
Telephone: +41 (43) 960 27 27, Mobile: +41 (79) 324 27 27
e-mail: andreas.karoussatos@gmail.com
