### ISSUE TITLE
Request: Download subtitles

### ISSUE THREAD

**Issue by djakupovic** [DonDavici/DreamPlex#151]
Most of the movies do not have any subtitles for every audio stream, e.g. german or english. It would be great, if you could download the subtitles in a /tmp folder and activate it automatically when it is downloaded. If it does not fit, the next one would be downloaded by the user

**Comment by rital06** [comment]
Hi Don, there are several ways of seeing this.
When subtitles are embedded in the video file the yellow button already does it.
When subtitles have already been downloaded (e.g. with subsdownload e2 plugin) to the Subs subfolder of the movie folder, you could allow the user to select the file to play and render it as OSD on too of the movie.
A much better development would be to enable a user to download and then render subtitles for a movie, in the same way the e2 subsdownload plugin does for movies in your hdd folder.

Hope it helps.

Cheers, rital06

**Comment by rital06** [comment]
Don, how do you prioritize between requested features?

**Comment by DonDavici** [comment]
it depends on the time i have and how much i do know what to do ;-)

as far as i know there are several ways to download subtitles with the plex server. with direct local configured this works now good i would say. just enable subtitle renaming in the settings of dreamplex.

hope this helps
