### ISSUE TITLE
version info cracked

### ISSUE THREAD

**Issue by DonDavici** [DonDavici/DreamPlex#224]
In 'über' wird immer noch Version 0.1 angezeigt...

**Comment by bergyla** [comment]
Über OpenATV Feed habe ich eine Dreamplex-Version 2.1.3+git1422+573d30b-r2 erhalten.
Es wird im Über Dialog immer noch eine Versionsnummer 0.1 angezeigt.
Ist der Fehler nun erneut eingebaut worden?
