### ISSUE TITLE
Direct Local and subtitles problem

### ISSUE THREAD

**Issue by herminus** [DonDavici/DreamPlex#252]
Hi. I have a Gigablue HD Quad Plus with DreamPlex, and a Ubuntu Server with Plex Server and the library. If i setup the Playback Type to "Direct Local" in the dreamplex, i can play movies, and chose the subtitle, but the subtitles (SRT) do not appear.

In streamed or transcoded mode, everything works.
This configuration is not supported?

Thank You.

**Comment by adrianmihalko** [comment]
I am using Opensubtitle Agent for automatic downloading subtitles. Is there any way to use these subtitles in direct local playback mode? (The agent stores elsewhere the subtitle file, not in the directory of the video)

**Comment by DonDavici** [comment]
for direct local it has to be in the same directory. sorry

**Comment by adrianmihalko** [comment]
Good to know that, then I am going to use subliminal for downloading subtitles.
