### ISSUE TITLE
ondeck wird von falschem user angezeigt

### ISSUE THREAD

**Issue by bender-tg** [DonDavici/DreamPlex#261]
OnDeck in der obersten Ebene zeigt den Inhalt von einem RemoteUser und nicht von mir. In der Film und Serien übersicht wird in OnDeck aber mein OnDeck angezeigt.

Verständlich?

**Comment by DonDavici** [comment]
hi
bitte probier das mal in der neuen beta43. sollte demnächst kommen ;-)

grüsse
