### ISSUE TITLE
subtitles

### ISSUE THREAD

**Issue by DonDavici** [DonDavici/DreamPlex#264]
Hi Don,

i have a problem with the subtitles.

I have installed betaversion 31 and when i use direct local as play mode no subs are apearring.

Normally when the movie is playing i press twice yellow and i can mark wit an X the sub that i want.
For now there`s no X marker and no subs, however when i change the play mode to transcode ther is a X marker and i can see the sub.

When i go back to betaversion 24 all is working fine with direct local.

Do you know what is wrong ?

TODO:
abklären ob mein override in direct local auch die auswahl verhindert bzw. den override fixen

**Comment by victordk** [comment]
I have the same problem with a Vu+ Solo 2 and DM500HD running Openpli 4.0. Subtitles does not work in streaming mode with latest beta build (37) but do work with stable version 2.0.3.

**Comment by victordk** [comment]
My issue is solved

**Comment by DonDavici** [comment]
great :-)
