### ISSUE TITLE
Update to revision showing up

### ISSUE THREAD

**Issue by 4n4n4s** [DonDavici/DreamPlex#267]
Everytime when I start DreamPlex the following notification pops up.

>Your current Version is 2.1.0-beta.31
>Update to revision 2.1.0-beta31 found!
>
>Do you want to update now?

So the versions are compared in a wrong way. (beta.31 and beta31)
This happens in your file called DP_SystemCheck.py
Thank you very much!

**Comment by wabee** [comment]
I have this issue too on Vu Solo2 with OpenPli

**Comment by DonDavici** [comment]
is fixed. update to beta32 :-)
