### ISSUE TITLE
Dreamplex decoding issue

### ISSUE THREAD

**Issue by acoding** [DonDavici/DreamPlex#271]
Hey Don,

I noticed another user spoke previously about this issue, I am now faced with this issue to (some mp4 files wont work. The message received is: 
 "Your Box can't decode this video stream!
Gstreamer plugin JPEG decoder not available"

You told that other user to check it out in v 2.1.0. I have now done so but am still having the issue. Any suggestions?

**Comment by DonDavici** [comment]
i would need some logfiles or more details
