### ISSUE TITLE
Multiuserfeature is marking for wrong user

### ISSUE THREAD

**Issue by DonDavici** [DonDavici/DreamPlex#272]
Ich habe da noch ein paar Fragen bzgl Multi-User.
Folgende Situation in meinem Heimnetzwerk:
1x Win Plexserver (Version 0.9.11.7) (als user1 angemeldet unter "verbinden" in den Settings)
1x Dreambox mit aktuellsten Beta 32 (als user1 angemeldet)
1x Dreambox mit Beta 31 (als user2 angemeldet)
Verbindung in den Settings mit IP, abgespielt über Direct Lokal und jeweils angemeldet bei myplex
Also 2x verschiedene Plex Accounts ohne Plex Pass, aber das sollte kein Problem sein da es seit Dezember gehen sollte

Das Abspielen funktioniert soweit, das einzige Problem was ich habe der user2 sieht das "Gesehen" und "Ungesehen" von user1. Er markiert die Filme auch bei user1 als "Gesehen"

**Comment by DonDavici** [comment]
kannst du mal bei beiden bitte boxen in den serversettings auf recreate token (blau) gehen. und dann nochmal testen.

merci

**Comment by UcBalu** [comment]
kann ich wahrscheinlich erst am WE testen :/

**Comment by UcBalu** [comment]
eine kurze Frage noch bevor ich das am WE teste, muss dann unter den Server Settings "my Plex Home Users" auf ja oder nein? (kein Plex Pass vorhanden)

**Comment by DonDavici** [comment]
das hat aus meiner sicht ja nichts mit homeuser zu tun. also auf nein.

**Comment by UcBalu** [comment]
das scheint noch nicht zu funktionieren
![unbenannt](https://cloud.githubusercontent.com/assets/10799984/6199717/ff6f42fa-b454-11e4-8367-92c1ddc74c56.JPG)

**Comment by DonDavici** [comment]
nochmal die frage ob du auch wirklich die tokens erneuert hast!?

**Comment by UcBalu** [comment]
ja, habe ich. Erst auf der neuesten Beta aktualisiert und dann den Token erneuert.

**Comment by DonDavici** [comment]
dieser Dj..... ist das der user 2 oder user 1? also wer ist der besitzer des servers also welcher user ist der angemeldete direkt auf dem server?

**Comment by UcBalu** [comment]
der DJ... ist User1 und besitzer des Servers. der User2 ist HorGis und als Freund eingetragen

**Comment by UcBalu** [comment]
kann ich dir noch irgendwelche Logs herstellen um den Fehler zu finden?

**Comment by DonDavici** [comment]
derzeit. nein. ich versuche es gerade nachzustellen. mal sehen :-)

**Comment by DonDavici** [comment]
nur zum besseren verständnis.

der server gehört DJ... der server ist unter diesem account angemeldet? horgis ist ein user mit dem geshared wird. also er hat dreamplex und unter myplex meldet er sich als horgis an? richtig?

**Comment by DonDavici** [comment]
schick mir bitte auf jeden fall noch ein aktuelles log file bitte. danke

**Comment by DonDavici** [comment]
kann es sein, dass die filme über die remotefunktion gestartet werden?

**Comment by UcBalu** [comment]
Hi,

Bei User2 wurden die über das Plugin gestartet und bei user1 kann es durchaus über iOS App gestartet worden sein. 

Gruß
