### ISSUE TITLE
Feature Request: Change audio track / language in transcoded mode

### ISSUE THREAD

**Issue by mationic** [DonDavici/DreamPlex#277]
Often I want to watch a movie in English instead of my system language (German).
In transcoded mode dreamplex automatically chooses the system language. While playing, the other audio tracks are not available (like in streamed mode). It would be nice if there would be a way to select the language or audio track of the movie in the menu beforehand.
For now, can I change the default language to English in the code somewhere?
I tried to set systemLanguage = "en" in setAudioTrack(), DP_Player.py without success - the transcoded audio track is still german.
Thanks for your help.

**Comment by DonDavici** [comment]
in my point of view this is working already. just press audio button before you start playback in the movie list :-)

**Comment by mationic** [comment]
You're right. Found the option on my Vu+. Unfortunately the AZBox doesn't have this audio button. I also couldn't find the audio menu on another button. :(

**Comment by DonDavici** [comment]
i added the radio button to start this feature as well in the latest beta :-)

**Comment by mationic** [comment]
Great! Thank you very much.
