### ISSUE TITLE
DM800HD se --- what is the best mode for the best picture /sound?      PC---> Dreamplex

### ISSUE THREAD

**Issue by shangi** [DonDavici/DreamPlex#278]
Hello,

I am using for some time with great pleasure Dreamplex without actually getting into the settings ..

I would like to optimize my Dreamplex experience, primarily using the most optimal mode for the best picture and sound for movies visonner.

- streamed
- Local Direct
- transcoded

Which one?

So I have a DM800HD is (original) with last image OpenPLi 4.0
with over Dreamplex stable version 2.0.3
I use a Panasonic Plasma full HD 50 ', and a Denon amplifier (DTS only, not HD, not HDMI)
And my server is my PC (using the latest version of Plex Media Server installed) directly connected to the dreambox by ethernet CAT6a , via the internet box (no wifi, no CPL)

Thank's in advance

**Comment by DonDavici** [comment]
hallo

i would say that direct local is always the best option if possible. it is more difficult to set up (shares and mappings) but if successfully configured it plays all your files like the internal mediaplayer would do.

greets

**Comment by DonDavici** [comment]
reopen if you need some more information :-)

**Comment by shangi** [comment]
Unfortunately, yes, I need to reopen.

I find it hard to configure the local direct mode (error messages films location ...)

Already can we use this local direct mode: Dreamplex ---- PC (connected via RJ45) or only nas linux?

Whether it be before adding a mount point in the network part of the dreambox? If so, can we do it in CIFS? (or only NFS / linux), and then again, if so, is it obligatoirment specify a username and password (PC and dreambox)

Thank you very much in advance
