### ISSUE TITLE
Cannot install DreamPlex

### ISSUE THREAD

**Issue by Silvercalibur** [DonDavici/DreamPlex#282]
Hi guys,

I'm hoping I can get some help regarding installing this and would very much appreciate any help anyone could give.

I have a technomate Nano OE and have FTP'd latest ipk file over to my tmp folder. I then use putty and telnet the command to install, however I keep getting the same error over and over.

I've never installed DreamPlex before so wont be an issue regarding that.

Here's an image of the error ; 

http://i.imgur.com/bS4nGzK.jpg

**Comment by DonDavici** [comment]
Hi,

just use 

opkg install --force-overwrite --force-depends ...

this will help :-)

**Comment by Silvercalibur** [comment]
Hi,

Thanks for that, so what's the exact command please ?..Im starting to think
there might be a problem with my receiver :/

**Comment by DonDavici** [comment]
just add the path to the file like

opkg install /tmp/filename.ipk --force-overwrite --force-depends

**Comment by Silvercalibur** [comment]
Ok thank you I will try this now :)

**Comment by Silvercalibur** [comment]
Don really appreciate your help, I have it installed now thank you :)

I now have a different problem lol..

When trying to sync my files I keep getting the an error saying "list index out of range"

Connected initially using "discover" but not sure why I can't sync files
