### ISSUE TITLE
configuration : direct local mode

### ISSUE THREAD

**Issue by shangi** [DonDavici/DreamPlex#283]
Hello,
I find it hard to configure the local direct mode (error messages films location ...)

Already can we use this local direct mode: Dreamplex --Box internet-- PC (connected via RJ45) or only nas linux?

Whether it be before adding a mount point in the network part of the dreambox? If so, can we do it in CIFS? (or only NFS / linux), and then again, if so, is it obligatoirment specify a username and password (PC and dreambox)

I use the latest stable version, perhaps it is necessary to use the latest beta version with support local direct mounting?

Thank you very much in advance

**Comment by DonDavici** [comment]
in the newest beta 44 there is now a direct local helper. check it out :-)

for direct local you need to mount your pc/nas whatever as cifs or nfs on your box. most images make their shares under /mnt/net

**Comment by shangi** [comment]
Hi,

So I managed to get my directory "Movies" from my PC to the network manager in dreambox cifs, I can play movies from the native video player dreambox (in picture OpenPLi).
However, the rertoire used for mounting is under "media / net / Films".

So that when I use the mapping function of beta 44 Dreamplex, "3" key and then blue button, he told me to check if the mounting mnt / net is working ....
"Media / net" and "mnt / net" is different ...

The exact path of the folder containing my movies on my pc as this one:
Hi,

So I managed to get my directory "Movies" from my PC to the network manager in dreambox cifs, I can play movies from the native video player dreambox (in picture OpenPLi).
However, the rertoire used for mounting is under "media / net / Films".

So that when I use the mapping function of beta 44 Dreamplex, "3" key and then blue button, he told me to check if the mounting mnt / net is working ....
"Media / net" and "mnt / net" is different ...

The exact path of the folder containing my movies on my pc as this one:
J:\Newsleecher Extract\Films

Moreover, when I try to change the destination path in the mapping in "server" and I try to read local live what I put, he gives me every time the same destination path (J:\Newsleecher Extract\Films), as if he had saved and it was impossible to change it .. maybe stopping enigma and editing a file Dreamplex ???

Moreover, when I try to change the destination path in the mapping in "server" and I try to read local live what I put, he gives me every time the same destination path (J \ Newsleecher Extract \ Films), as if he had saved and it was impossible to change it .. maybe stopping enigma and editing a file Dreamplex ???

**Comment by shangi** [comment]
PS: In / media/dd/dreamplex/config, i have "mountMappings" and its content that : 
<xml>
  <server id="0">
    <mapping id="1" localPathPart="/mnt/net/Films/" remotePathPart="C:\Videos or /volume1/videos or \\SERVER\Videos\films" />
    <mapping id="2" remotePathPart="\media\nettt\" localPathPart="/media/net/Films/" />
  </server>
</xml>
---

**Comment by shangi** [comment]
Just one little thing, reading by "direct local", there he needs to install a video player plugin in particular? (EMC, MoviePlayer, VLC ...).
Or native player built into my image is enough for reading? (Image OpenPLi)

Thank you in advance

**Comment by DonDavici** [comment]
The internal player is enough. No need to install something else ;-)

Von meinem iPhone gesendet

**Comment by shangi** [comment]
Ok thank you for everything,
And thank you for your outstanding work.
really great
