### ISSUE TITLE
Crash using 1080 skins using 2.1.0 beta 42

### ISSUE THREAD

**Issue by ViX-Sicilian** [DonDavici/DreamPlex#284]
As the title, crash using 1080 skins. Below is taken from 3 crashlogs.

[AutoTimer] Auto Poll Enabled
('skin: default', None, 'D')
('skin: Plex_Experience', None, 'D')
('skin: YouPlex-Blue', None, 'D')
EXCEPTION IN PYTHON STARTUP CODE:
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/mytest.py", line 685, in <module>
    runScreenTest()
  File "/usr/lib/enigma2/python/mytest.py", line 489, in runScreenTest
    plugins.readPluginList(resolveFilename(SCOPE_PLUGINS))
  File "/usr/lib/enigma2/python/Components/PluginComponent.py", line 104, in readPluginList
  File "/usr/lib/enigma2/python/Components/PluginComponent.py", line 30, in addPlugin
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/plugin.py", line 71, in Autostart
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/__init__.py", line 464, in prepareEnvironment
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/__init__.py", line 409, in getViewTypesForSettings
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/__init__.py", line 425, in getViewsByType
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/DP_ViewFactory.py", line 99, in getViews
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/DP_ViewFactory.py", line 178, in getViewsFromSkinParams
Exception
------------------------------------------------------------
(exit code 5)
]]>
		</enigma2crashlog>
	</crashlogs>
</openvix>

________________________________________________________________________________
ERROR: accelAlloc failed
KEY: 139 MENU
KEY: 352 OK
action ->  OkCancelActions ok
[SKIN] No skin to read...
warning, skin is missing element miniTv in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
warning, skin is missing element 0 in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
warning, skin is missing element +2 in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
warning, skin is missing element +1 in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
warning, skin is missing element -1 in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
warning, skin is missing element -2 in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
<enigma.eVideoWidget; proxy of <Swig Object of type 'eVideoWidget *' at 0x241da10> >
KEY: 352 OK
[EPGC] abort non avail schedule other reading
[EPGC] abort non avail netmed schedule reading
[EPGC] abort non avail netmed schedule other reading
[EPGC] abort non avail FreeSat schedule_other reading
[EPGC] abort non avail viasat reading
Start timeshift!
recording to /media/usb/timeshift/timeshift.VkPDdt
setIoPrio realtime level 7 ok
[eFilePushThreadRecorder] THREAD START
[Timeshift] type object 'eEPGCache' has no attribute 'getinstance'
eDVBServicePlay::unpause
KEY: 174 EXIT
action ->  DP_MainMenuActions cancel
ignore request to play already running service(1)
KEY: 174 EXIT
KEY: 352 OK
action ->  OkCancelActions ok
[SKIN] No skin to read...
warning, skin is missing element miniTv in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
warning, skin is missing element 0 in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
warning, skin is missing element +2 in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
warning, skin is missing element +1 in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
warning, skin is missing element -1 in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
warning, skin is missing element -2 in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
<enigma.eVideoWidget; proxy of <Swig Object of type 'eVideoWidget *' at 0x241d920> >
KEY: 352 OK
[EPGC] nownext finished(1425326457)
[EPGC] virgin nownext finished(1425326457)
KEY: 108 DOWN
action ->  DP_MainMenuActions down
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 48, in action
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/DP_MainMenu.py", line 240, in down
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/DP_MainMenu.py", line 259, in right
  File "/usr/lib/enigma2/python/Components/Sources/List.py", line 76, in selectNext
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
(PyObject_CallObject(<bound method HelpableActionMap.action of <Components.ActionMap.HelpableActionMap instance at 0x249c800>>,('DP_MainMenuActions', 'down')) failed)
]]>
		</enigma2crashlog>
	</crashlogs>
</openvix>

______________________________________________________________________________________

[SKIN] No skin to read...
warning, skin is missing element miniTv in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
warning, skin is missing element 0 in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
warning, skin is missing element +2 in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
warning, skin is missing element +1 in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
warning, skin is missing element -1 in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
warning, skin is missing element -2 in <class 'Plugins.Extensions.DreamPlex.DP_MainMenu.DPS_MainMenu'>
<enigma.eVideoWidget; proxy of <Swig Object of type 'eVideoWidget *' at 0x255d0f8> >
KEY: 352 OK
KEY: 108 DOWN
action ->  DP_MainMenuActions down
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 48, in action
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/DP_MainMenu.py", line 240, in down
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/DP_MainMenu.py", line 259, in right
  File "/usr/lib/enigma2/python/Components/Sources/List.py", line 76, in selectNext
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
(PyObject_CallObject(<bound method HelpableActionMap.action of <Components.ActionMap.HelpableActionMap instance at 0x255c418>>,('DP_MainMenuActions', 'down')) failed)
]]>
		</enigma2crashlog>
	</crashlogs>
</openvix>

**Comment by ViX-Sicilian** [comment]
Possibly an issue with this? https://github.com/DonDavici/DreamPlex/commit/33b5f165d9468951e07af8559e6856ed0f194d6e

**Comment by andyblac** [comment]
DP HAS to be setup fresh, please remove ANY 'dreamplex' lines from you e2 settings file, and retry.

**Comment by DonDavici** [comment]
any news?

**Comment by ViX-Sicilian** [comment]
Just done a complete fresh flash and setup on a VU+ Duo2.

No longer crashing, but if use switches to a 1080 skin then tries opens Dreamplex, user is not able to see any menus/options in dreamplex, only small TV in corner. Only way round this is as follows: -

1) Start with standard 720 skins.
2) Install Dreamplex.
3) Install 1080 skin.
4) Install 1080 dreamplex skin.
5) Open Dreamplex using 720 skin.
6) Set new 1080 skin in Dreamplex settings.
7) Swtich to 1080 main skin.
8) Start Dreamplex, should now start ok.

This wasn't the behaviour before, before you user could open dreamplex no matter is user using 720 or 1080 skin.

**Comment by DonDavici** [comment]
Hi,


FHD skin of Dreamplex only works if the skin of the box is also FHD.

with default there is a autoswitch between the resolutions.

not sure if i get you right. but the user has to select on its own what
skin he wants to use. but actually they should only choose FHD if the box
is FHD too.

greets

2015-03-07 11:41 GMT+01:00 ViX-Sicilian <notifications@github.com>:

**Comment by andyblac** [comment]
you can not use a 1080p skin in DP without using a 1080p in E2, as the framebuffer will not be at 1080p, as DP will still be using a 720p framebuffer, so it is like try to view a 1080p picture in PhotoShop at 100% view it will not fit, it needs to be zoomed out, 

so to use a 1080p skin in DP first install 1080p skin in E2.

hope this clears it up.
