### ISSUE TITLE
VIX spinner starting Dreamplex 

### ISSUE THREAD

**Issue by webblet** [DonDavici/DreamPlex#289]
Hi,
I'm running Dreamplex 2.1.0  beta 51 and Vix Apollo 153 on a VU+ Solo2.
When I start dreamplex, I just get the VIX spinner. It was workiing about a week ago and I was running beta37 and then it just started freezing like this. Once its started it just hangs indefinately intil I swict the VU+ off. I tried upgrading to beta 51 with no change. I also tried doing a re-flash on the VU to no avail.
I saw a previous reporting of this as issue  228 and you suggested starting a telnet session.

All I get is 

action ->  OkCancelActions ok
<enigma.eVideoWidget; proxy of <Swig Object of type 'eVideoWidget *' at 0x20216f8> >
main thread is non-idle! display spinner!

No log file is created.

**Comment by DonDavici** [comment]
Hi,

this error seems to be related to autoupdate check.

connect to the box via shh or telnet.

enter "init 4"
than edit /etc/enigma/settings

in the line with dreamplex check for update exchange true with false=> save

after that just type "init 3" and everything should work again.

greets

2015-03-11 19:51 GMT+01:00 webblet <notifications@github.com>:

**Comment by webblet** [comment]
Yes thats fixed it - Thanks very much!
I wish I'd posted here hours ago  - could have saved myself a lot of effort!

Thanks again

**Comment by DonDavici** [comment]
i am glad to heard that this fixed your problem. sorry for any
inconvienience.

greets
<http://www.dict.cc/englisch-deutsch/to+be+an+inconvenience+to+sb.html>

2015-03-11 20:20 GMT+01:00 webblet <notifications@github.com>:
