### ISSUE TITLE
Can't update from 2.1.0-beta54 to 2.1.0 stable

### ISSUE THREAD

**Issue by adrianmihalko** [DonDavici/DreamPlex#291]
Hi,

Which is newer DreamPlex - 2.1.0-beta54 or 2.1.0 stable? I have DreamPlex - 2.1.0-beta54 installed, but there is no update dialog on the startup to upgrade to 2.1.0 stable.

**Comment by jbollacke** [comment]
Use

`opkg install --force enigma2-plugin-extensions-dreamplex_2.1.0_all.ipk`

b/c opkg thinks that installing 2.1.0 over 2.1.0-beta54 is a downgrad.

**Comment by DonDavici** [comment]
should be fixed with the comment above or with installing the new 2.1.1 ;-)

**Comment by adrianmihalko** [comment]
It's working now, thank you very much. :)

BTW: I sometimes see rotary gear icon and the box freezes - it's related to DreamPlex? Maybe it is updating library, or something like that?
