### ISSUE TITLE
Feature request: language description in subtitle support

### ISSUE THREAD

**Issue by bpwats** [DonDavici/DreamPlex#53]
Hello Dondavici, I see you started work on subtitles implementation. Great!

Hopefully I can add this minor feature request:
Plex has the ability to only display subtitles when audio language is different from (preferred) subtitle language, instead of simply always displaying subtitles.
For this to work, Plex needs to know what language the subtitle(s) are in. It knows this by adding a three letter language code in the filename, right before the .srt extension.
Example: "tvshow.nld.srt" to go along with "tvshow.mp4" in the same directory.
Then also the subtitle language will show in the Plex interface, in this example "Dutch".

I found and now use this wonderful tool called "FileBot.app" (http://www.filebot.net) to rename and download subtitles for (downloaded) TV shows. It has the language descriptor by default in the subtitle file name.

However, since subs2downloader (the extension I use on the dreambox to play my TV shows) does not see identical file names anymore, the subtitle cannot be enabled (by pressing Audio > subtitles enter). I would need to take out the language descriptor again.

Perhaps you can find a way to support language description in subtitles "Plex style"?

**Comment by DonDavici** [comment]
implemented in 2.1.0
